create TABLE Campus(
	Campus_ID INT PRIMARY KEY NOT NULL,
	CAMPUS_NAME VARCHAR(24) NULL,
	CAMPUS_ADDRESS VARCHAR(24) NULL,
	CAMPUS_CITY VARCHAR(24) NULL
	)
CREATE TABLE Teacher(
	TEACHER_ID INT PRIMARY KEY NOT NULL,
	TEACHER_NAME VARCHAR(24) NULL,
	TEACHER_SALARY NUMERIC(3,2) NULL,
	)
CREATE TABLE Program(
	PROGRAM_ID INT PRIMARY KEY NOT NULL,
	PROGRAM_NAMES VARCHAR(24) NULL,
	PROGRAM_DESCRIPTION VARCHAR(2000) NULL,
	TUITION_FEES NUMERIC(7,2) NULL,
	PROGRAM_COORDINATOR_ID INT FOREIGN KEY REFERENCES Teacher(TEACHER_ID),
	CAMPUS_ID INT FOREIGN KEY REFERENCES Campus(CAMPUS_ID)
	)
CREATE TABLE Course(
	COURSE_ID INT PRIMARY KEY NOT NULL,
	COURSE_NAME VARCHAR(24) NULL,
	COURSE_SEMESTER VARCHAR(24) NULL,
	PROGRAM_ID INT FOREIGN KEY REFERENCES Program(PROGRAM_ID) NULL,
	TEACHER_ID INT FOREIGN KEY REFERENCES Teacher(TEACHER_ID) NULL
	)
CREATE TABLE Student(
	STUDENT_ID INT PRIMARY KEY NOT NULL,
	STUDENT_NAME VARCHAR(24) NULL,
	STUDENT_TYPE VARCHAR(24) NULL,
	STUDENT_ADMISSION_DATE DATE NULL,
	STUDENT_GPA NUMERIC(3,2) NULL,
	PROGRAM_ID INT FOREIGN KEY REFERENCES Program(PROGRAM_ID) NULL
	)





