USE HR;
GO

SELECT SALARY 
FROM EMPLOYEES 
WHERE FIRST_NAME = 'Amit' OR FIRST_NAME = 'Nancy';

SELECT COUNTRY_NAME
FROM COUNTRIES
WHERE COUNTRY_NAME LIKE 'ZA%';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '__A_A';

SELECT * 
FROM LOCATIONS 
WHERE STATE_PROVINCE IS NULL; 

SELECT FIRST_NAME, SALARY, EMAIL, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE ASC,FIRST_NAME DESC;

SELECT JOB_TITLE 
FROM JOBS
WHERE MAX_SALARY NOT BETWEEN 2000 AND 5000;